server:
  port: 8088     # tomcat端口server

spring:
  datasource:   # 数据库连接
    url: jdbc:mysql://localhost:3306/purchase-sale-storage?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&userSSL=false
    username: firefly
    password: 123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  # 配置当前要使用的数据源的操作类型
    dbcp2:              # 数据库连接池的配置
      min-idle: 5       # 数据库连接的最小维持连接数
      initial-size: 5   # 初始化提供的连接数
      max-total: 5        # 最大的连接数
      max-wait-millis: 200     # 等待连接获取的最大超时时间

mybatis:                # Mybatis 扫描
  mapper-locations: classpath*:mapper/*.xml   # mapper映射文件位置
  type-aliases-package: com.liujl.purchasesalestorage.domain  # 开启别名
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名
  # config-location: classpath:mybatis-config.xml # mybatis配置文件所在路径

